### ISSUE TITLE
about joint detector

### ISSUE THREAD

**Issue by HW140701** [jackyjsy/CVPR21Chal-SLR#11]
Why not use openpose, alphapose joint detector？The current joint detector hrnet is slower than alphapose and openpose?

**Comment by jackyjsy** [comment]
Hi there, OpenPose and AlphaPose are faster, but we care more about accuracy and less about speed during this CVPR challenge, especially the accuracy for hands keypoints. That's why we chose the HRNet trained on whole-body pose dataset. 

As a bottom-up method, OpenPose is less accurate than most top-down methods. I haven't checked out the new version of AlphaPose yet (which includes the hands and feet keypoints). It might also be a reasonable choice if it is accurate enough.

**Comment by HW140701** [comment]
Thank you for your reply, and thank you for the open source code.
