### ISSUE TITLE
Problem in directories provided in https://github.com/jackyjsy/CVPR21Chal-SLR/tree/main/SL-GCN

### ISSUE THREAD

**Issue by EvgeniaChroni** [jackyjsy/CVPR21Chal-SLR#13]
In the instructions for Finetune and Test there is probably a mistake in the paths used for yaml files. 
Both test_joint.yaml and train_joint.yaml use the same directory : 
config/sign/finetune which is not true. 

Could you please let me know which are the correct  directories?

**Comment by jackyjsy** [comment]
Thanks for pointing it out. It seems to be a typo in the readme.md file. It is fixed in commit [b693657](https://github.com/jackyjsy/CVPR21Chal-SLR/commit/b6936574ca33b3d84bc404a0bf6b4707c71c3e81). Please check [SL-GCN/readme.md](https://github.com/jackyjsy/CVPR21Chal-SLR/blob/main/SL-GCN/readme.md) for the updated version.
